### ISSUE TITLE
Error while Downloading

### ISSUE THREAD

**Issue by theactiveone** [rockihack/Stud.IP-FileSync#13]
I am using version 1.1.0 on Windows 10 with openjdk 13.0.2. 

When I try to run the Snyc operation I get: 

```
java.lang.IllegalStateException: Statuscode: 500
	at de.uni.hannover.studip.sync.models.RestApi.downloadDocumentById(RestApi.java:126)
	at de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob.run(DownloadDocumentJob.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

```` 

And the download only gets partially done. 

The complete command line output looks like: 

```java.lang.IllegalStateException: Statuscode: 500
        at de.uni.hannover.studip.sync.models.RestApi.downloadDocumentById(RestApi.java:126)
        at de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob.run(DownloadDocumentJob.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Apr. 20, 2020 12:25:32 PM de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob run
WARNING: Removed document: ML_Sec1Einleitung.pdf
java.lang.IllegalStateException: Statuscode: 500
        at de.uni.hannover.studip.sync.models.RestApi.downloadDocumentById(RestApi.java:126)
        at de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob.run(DownloadDocumentJob.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Apr. 20, 2020 12:25:32 PM de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob run
WARNING: Removed document: CV_Kap1Summary.pdf
java.lang.IllegalStateException: Statuscode: 500
        at de.uni.hannover.studip.sync.models.RestApi.downloadDocumentById(RestApi.java:126)
        at de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob.run(DownloadDocumentJob.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.IllegalStateException: Statuscode: 500
        at de.uni.hannover.studip.sync.models.RestApi.downloadDocumentById(RestApi.java:126)
        at de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob.run(DownloadDocumentJob.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)```

**Comment by rockihack** [comment]
I got that same error after the stud.ip upgrade and resolved it by logging out and in again.
Dont know exactly whats wrong but the http status code 500 indicates a server error.

**Comment by theactiveone** [comment]
Unfortunately it does not fix the problem for me. I even deleted all the config files and choose a new folder. I still get: 
`java.lang.IllegalStateException: Statuscode: 500
at de.uni.hannover.studip.sync.models.RestApi.downloadDocumentById(RestApi.java:126)
at de.uni.hannover.studip.sync.models.jobs.DownloadDocumentJob.run(DownloadDocumentJob.java:82)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)`

**Comment by rockihack** [comment]
Stud.IP sends status code 500 instead of 404 when the file does not exist.
Its that bad...

https://develop.studip.de/trac/browser/trunk/app/routes/FileSystem.php#L49

What kind of file produces this error?

**Comment by theactiveone** [comment]
I don't think I am able to see which file causes this error. Is there a way to make the output more verbose? My guess is that either links/URLs or files with missing download permissions are causing this problem.

**Comment by rockihack** [comment]
Can you please test if pull request #14 fixes the issue?

**Comment by theactiveone** [comment]
I would like to but I have neither a running StudIp test instance nor a developer key. Could you provide a compiled version containing the developer key for Uni Hannover?

**Comment by rockihack** [comment]
Here you go:
http://dev.lennart-glauer.de/filesync/filesync-issue13.zip

**Comment by theactiveone** [comment]
That fixed it for me! Thank very much!
